import Link from "next/link";
import { notFound } from "next/navigation";
import { getDnsIndicator } from "@/lib/indicators";
import { sourceDetailHrefForUrl } from "@/lib/sources/public-registry";

export default async function IndicatorPage({ params }: { params: Promise<{ indicatorId: string }> }) {
  const { indicatorId } = await params; const item = getDnsIndicator(indicatorId); if (!item) notFound();
  return <div className="shell content-page"><header className="page-intro"><p className="eyebrow">{item.indicator_id} · Deutsche Nachhaltigkeitsstrategie</p><h1>{item.official_name_2025}</h1><p className="lead">{item.official_definition || "Die amtliche Quelle weist keine eigenständige Definition aus."}</p></header><dl className="government-impact-summary"><div><dt>Politische Intention</dt><dd>{item.official_political_intention || "amtlich nicht ausgewiesen"}</dd></div><div><dt>Ziel 2025</dt><dd>{item.official_target_text_2025}</dd></div><div><dt>Zieltyp</dt><dd>{item.official_target_type || "amtlich nicht ausgewiesen"}</dd></div><div><dt>Datenstand</dt><dd>{item.official_data_state || "amtlich nicht ausgewiesen"}</dd></div><div><dt>Einheit</dt><dd>{item.data_summary.units.join(", ") || "amtlich nicht ausgewiesen"}</dd></div><div><dt>Zeitreihe</dt><dd>{item.data_summary.first_year ?? "offen"}–{item.data_summary.latest_year ?? "offen"} · {item.data_summary.observation_count} Beobachtungen</dd></div></dl>{item.comparability_notes.length > 0 && <section><h2>Vergleichbarkeit und Brüche</h2><ul>{item.comparability_notes.map((note) => <li key={note}>{note}</li>)}</ul></section>}<section className="notice"><strong>Keine automatische Wirkungszuordnung</strong><p>Für diesen amtlichen Messwert ist kein maschineller Zieltreffer als fachliche WÖk-Zuordnung veröffentlicht. Wirkung, Zurechnung und Empfehlung benötigen einen eigenen Review.</p></section><p><Link className="text-link" href={sourceDetailHrefForUrl(item.source_page_url)}>Amtliche Quelle im Quellenarchiv einordnen →</Link></p><p className="page-return"><Link href="/methodik/wirkindikatoren">← Alle DNS-Indikatoren</Link></p></div>;
}
