import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const source = (file: string) => readFileSync(file, "utf8");

test("DNS registry contains exactly 82 official source indicators without public machine mappings", () => {
  const registry = JSON.parse(source("data/indicators/dns-official-registry.json"));
  assert.equal(registry.record_count, 82);
  assert.equal(new Set(registry.records.map((item: { indicator_id: string }) => item.indicator_id)).size, 82);
  assert.ok(registry.records.every((item: { mapping_status: string; score_or_direction_inference: string }) => item.mapping_status === "NO_FACH_REVIEWED_WOEK_MAPPING" && item.score_or_direction_inference === "FORBIDDEN"));
});

test("Masterregister release contract preserves the authoritative 621 records", () => {
  const manifest = JSON.parse(source("data/indicators/masterregister-release-manifest.json"));
  assert.equal(manifest.authoritative_item_count, 621);
  assert.equal(manifest.unique_id_count, 621);
  assert.equal(manifest.duplicate_id_count, 0);
  assert.equal(manifest.publication_rule, "NO_MACHINE_MAPPING_AS_FACH_REVIEW");
});

test("Government, Parliament and EU share the fail-closed problem and common-target components", () => {
  for (const file of ["app/components/government/GovernmentImpactCase.tsx", "app/components/eu/EuImpactCase.tsx", "app/entscheidungen/[slug]/page.tsx"]) {
    const contents = source(file);
    assert.match(contents, /ProblemGoalReview/);
    assert.match(contents, /CommonTargetsComparison/);
    assert.ok(contents.indexOf("<ProblemGoalReview") < contents.indexOf("<RecommendationSection"));
    assert.ok(contents.lastIndexOf("<RecommendationSection") < contents.lastIndexOf("<CommonTargetsComparison"));
  }
});

test("reference layers stay separated and open values never become scores", () => {
  const method = source("lib/decision-method.ts");
  const component = source("app/components/DecisionMethodLayers.tsx");
  for (const layer of ["FUNDAMENTAL_RIGHTS_AND_CONSTITUTIONAL_PRINCIPLES", "STATE_GOALS_AND_OTHER_LEGAL_BINDINGS", "UN_SDG", "WOEK_SDGPLUS", "WOEK_MPD", "GERMAN_SUSTAINABLE_DEVELOPMENT_STRATEGY_2025", "SUSTAINABILITY_ACTION_PLAN_2026", "WOEK_BOUNDARIES_AND_NON_COMPENSATION", "SCIENTIFIC_THRESHOLDS_RESILIENCE_GENERATIONS"]) assert.match(method, new RegExp(layer));
  assert.match(component, /fachlich noch offen/);
  assert.match(component, /weder eine arithmetische Gesamtnote noch einen automatisch erzeugten Zielbezug/);
  assert.doesNotMatch(component, /CANDIDATE_MACHINE|net_score|party_score|person_score/);
  assert.match(component, /relation_or_expected_direction/);
  assert.match(component, /mechanism_link_or_reason/);
  assert.match(component, /evidence_or_review_status/);
  assert.match(component, /sourceDetailHrefForUrl/);
});

test("recommendations remain canonical records and are never generated by the method layer", () => {
  const component = source("app/components/DecisionMethodLayers.tsx");
  assert.match(component, /recommendationForImpactCase/);
  assert.doesNotMatch(component, /generateRecommendation|inferRecommendation|recommendation_status\s*=/);
});
