export const governmentActionThemeTerms: Record<string, string[]> = {
  Wirtschaft: ["wirtschaft", "unternehmen", "industrie", "handel"],
  Energie: ["energie", "strom", "gas", "netz"],
  Klima: ["klima", "emission", "co2"],
  Gebäude: ["gebäude", "heizung", "wohnen"],
  Gesundheit: ["gesundheit", "krankenhaus", "medizin", "pflege"],
  Arbeit: ["arbeit", "beschäftigung", "tarif"],
  Soziales: ["sozial", "grundsicherung", "familie", "kindergeld"],
  Rente: ["rente", "altersvorsorge"],
  Verkehr: ["verkehr", "bahn", "straße", "mobilität"],
  Digitalstaat: ["digital", "daten", "online"],
  Forschung: ["forschung", "wissenschaft"],
  Bildung: ["bildung", "schule", "ausbildung"],
  Migration: ["migration", "asyl", "aufenthalt"],
  Sicherheit: ["sicherheit", "bundeswehr", "polizei", "schutz"],
  Landwirtschaft: ["landwirtschaft", "tier", "ernährung"],
  Verbraucherschutz: ["verbraucher"],
  "Internationale Politik": ["international", "europ", "abkommen"],
  Entwicklungspolitik: ["entwicklungspolitik", "entwicklungszusammenarbeit"],
};
