import { sourceHealth } from "./newsroom.mjs";

const STATUS_LABELS = {
  active: "Aktiv abgerufen", disturbed: "Abruf gestört", stale: "Abruf überfällig", stale_content: "Abruf erfolgreich, neuester Inhalt auffällig alt",
  configured_not_yet_verified: "Eingerichtet, erster erfolgreicher Lauf noch offen",
  no_free_access: "Kein freier direkter Zugang eingerichtet", pending: "Zugang in Prüfung",
  excluded: "Redaktionell ausgeschlossen", disabled: "Deaktiviert",
};
const KIND_LABELS = { institution: "Institution / Primärquellenangebot", journalism: "Journalistisches Medium", public_broadcasting: "Öffentlich-rechtliches Medium", specialist_journalism: "Fachjournalismus", science_mediation: "Wissenschaftsvermittlung", agency: "Nachrichtenagentur", ngo: "Nichtregierungsorganisation", own_publication: "Eigene WÖk-Veröffentlichung" };

export function buildSourcePages(registry, state, { pageShell, write, escapeHtml: esc, root, site, formatDate }) {
  const asOf = state.last_attempted_run || registry.updated_at;
  const publishers = new Map();
  for (const source of registry.sources) {
    const id = source.publisher_id || source.source_id;
    publishers.set(id, [...(publishers.get(id) || []), source]);
  }
  const records = [...publishers].map(([id, sources]) => ({ id, source: sources.find((source) => source.why_relevant) || sources[0], sources, health: sources.map((source) => sourceHealth(source, state, asOf)) })).sort((a, b) => a.source.name.localeCompare(b.source.name, "de"));
  const routes = ["wirkungsticker/quellen/"];
  const profileLink = (id) => `${site}/wirkungsticker/quellen/${id}/`;
  const accessNote = "Es werden keine Nachrichten-Abos oder kostenpflichtigen Agentur- und Nachrichten-APIs gekauft. Login-Schranken und Paywalls werden nicht umgangen, auch nicht über Drittanbieter. Bei gesperrten Artikeln suchen wir freie Originalquellen und unabhängige Berichte. Fehlen belastbare Belege, wird nicht als gesichert veröffentlicht.";
  const explanation = "Diese Übersicht beschreibt Herausgeber und deren eingerichtete Recherchezugänge. Sie ist nicht das Literatur-Quellenarchiv und kein Qualitätsranking. Ob eine Quelle Primärquelle, journalistische Bestätigung, Interessenäußerung oder Kontext liefert, entscheidet sich am einzelnen Dokument und an der jeweiligen Behauptung. Mehrere Abdrucke derselben Agenturmeldung sind keine unabhängigen Bestätigungen.";
  const cards = records.map(({ id, source, health }) => `<article class="info-card quellenarchiv-card"><p class="hero-kicker">${esc(KIND_LABELS[source.publisher_kind] || "Recherchequelle")}</p><h2><a href="${esc(id)}/">${esc(source.name)}</a></h2><p>${esc(source.why_relevant || `Recherche zu ${source.topic || "Politik, Wirtschaft und Gesellschaft"}. Jeder konkrete Beitrag wird gesondert auf Neuigkeit, materielle Relevanz und Evidenz geprüft.`)}</p><p>${[...new Set(health.map((item) => STATUS_LABELS[item.status] || item.status))].map(esc).join(" · ")}</p><a class="text-link" href="${esc(id)}/">Quellenprofil und Abrufstatus</a></article>`).join("\n");
  const body = `<main id="main-content" data-search-content data-no-glossary><article class="article-shell"><nav class="breadcrumb" aria-label="Brotkrumen"><a href="../">Wirkungsticker</a> / Quellen</nav><header class="term-detail-hero"><p class="hero-kicker">Transparente Recherchebasis</p><h1>Quellen &amp; Auswahlkriterien</h1><p class="lead">${esc(explanation)}</p><p>${records.length} Herausgeberprofile · ${registry.sources.filter((source) => source.enabled).length} eingerichtete Zugänge · Datenstand ${esc(formatDate(asOf))}</p></header><section class="term-summary-card"><h2>Nur kostenlose, öffentliche Recherchezugänge</h2><p>${esc(accessNote)}</p></section><section class="term-section-card"><h2>Relevanz statt Markenrangliste</h2><p>Wir prüfen Neuigkeit, Zahl und Art der Betroffenen, Intensität, Dauer, Reversibilität, Verteilung sowie System- und Schutzraumbezug. Interviews, regionale Recherchen und NGO-Studien können relevant sein. Reichweite und Aufmerksamkeit sind kein Wirkungsnachweis. Ein Quellenausschluss wird als redaktionelle Entscheidung kenntlich gemacht; politische Perspektive allein ist kein pauschales Ausschlusskriterium.</p><p>„Aktiv abgerufen“ bedeutet einen erfolgreichen technischen Abruf am angegebenen Stand, nicht die Übernahme aller Inhalte oder eine Garantie vollständiger Nachrichtenabdeckung. Störungen, ungeklärte Zugänge und reine Recherchemetadaten werden getrennt angezeigt.</p><p><a class="text-link" href="../../quellenarchiv/">Literatur- und Dokumentquellen im Quellenarchiv</a> · <a class="text-link" href="../#methodik">Methodik des Wirkungstickers</a></p></section><div class="card-grid">${cards}</div></article></main>`;
  write(`${root}/wirkungsticker/quellen/index.html`, pageShell({ title: "Quellen & Auswahlkriterien des Wirkungstickers", description: "Herausgeberprofile, Relevanz, Interessen, kostenlose Recherchezugänge und tatsächlicher Abrufstatus des Wirkungstickers.", canonical: `${site}/wirkungsticker/quellen/`, base: "../../", body, jsonLd: { "@context": "https://schema.org", "@type": "CollectionPage", name: "Quellen des Wirkungstickers", url: `${site}/wirkungsticker/quellen/`, mainEntity: { "@type": "ItemList", itemListElement: records.map(({ id, source }, index) => ({ "@type": "ListItem", position: index + 1, name: source.name, url: profileLink(id) })) } } }));
  for (const { id, source, sources, health } of records) {
    const why = source.why_relevant || `Die Quelle liefert Informationen zu ${[...new Set(sources.map((item) => item.topic).filter(Boolean))].join(", ") || "öffentlichen und wirtschaftlichen Vorgängen"}. Ob ein konkreter Beitrag relevant ist, wird ereignisbezogen geprüft.`;
    const context = source.editorial_context || (source.primary_source ? "Selbstauskunft einer Institution: Primärquelle für eigene Entscheidungen, Dokumente oder Veröffentlichungen. Eine Ankündigung belegt nicht automatisch Umsetzung, Erfolg oder Kausalität. Interessenkonflikte, Gegenbefunde und unabhängige Recherche sind einzubeziehen." : "Journalistische Darstellung oder Kontextquelle. Eigene Recherche, Agenturübernahme, Kommentar und Interessenäußerung sind zu unterscheiden. Die Herkunft allein bestätigt keine Behauptung.");
    const facts = [["Quellentyp", KIND_LABELS[source.publisher_kind] || source.publisher_kind], ["Themen", [...new Set(sources.map((item) => item.topic).filter(Boolean))].join(", ")], ["Räume", [...new Set(sources.flatMap((item) => item.geography || []))].join(", ")], ["Sprache", [...new Set(sources.map((item) => item.language || "de"))].join(", ")], ["Herausgeber-ID", id]];
    const feeds = sources.map((entry, index) => `<section class="term-section-card"><h3>${esc(entry.name)}</h3><dl class="source-facts">${[["Status", STATUS_LABELS[health[index].status] || health[index].status], ["Letzter erfolgreicher Abruf", health[index].last_success ? formatDate(health[index].last_success) : "Noch nicht nachgewiesen"], ["Neueste bekannte Quellmeldung", health[index].latest_item ? formatDate(health[index].latest_item) : "Kein verlässliches Datum im Abrufstand"], ["Verfahren", entry.source_type], ["Prüfintervall", entry.enabled ? `Etwa ${health[index].interval_minutes} Minuten; bei Störung begrenzter Backoff` : "Kein automatischer Abruf"], ["Inhaltszugang", entry.access?.article === "bounded_public_text" ? "Begrenzter öffentlicher Quellentext, flüchtig zur Prüfung" : "Nur Recherchemetadaten oder deaktiviert; kein Artikelvolltext"]].map(([key, value]) => `<div class="source-fact"><dt>${esc(key)}</dt><dd>${esc(value)}</dd></div>`).join("")}</dl>${entry.access?.note ? `<p>${esc(entry.access.note)}</p>` : ""}${entry.access?.terms_url ? `<p><a class="text-link" href="${esc(entry.access.terms_url)}" target="_blank" rel="noopener noreferrer">Angaben des Anbieters zum Angebot / Zugang</a></p>` : ""}</section>`).join("\n");
    const profile = `<main id="main-content" data-search-content data-no-glossary><article class="article-shell quellenarchiv-detail"><nav class="breadcrumb" aria-label="Brotkrumen"><a href="../../">Wirkungsticker</a> / <a href="../">Quellen</a> / ${esc(source.name)}</nav><header class="term-detail-hero"><p class="hero-kicker">Herausgeberprofil</p><h1>${esc(source.name)}</h1><p class="lead">${esc(why)}</p><p><a class="btn btn-secondary" href="${esc(source.url)}" target="_blank" rel="noopener noreferrer">Zur Originalquelle</a></p></header><section class="term-summary-card"><h2>Auf einen Blick</h2><dl class="source-facts">${facts.map(([key, value]) => `<div class="source-fact"><dt>${esc(key)}</dt><dd>${esc(value || "Nicht angegeben")}</dd></div>`).join("")}</dl></section><div class="term-section-grid"><section class="term-section-card"><h2>Warum relevant?</h2><p>${esc(why)}</p></section><section class="term-section-card"><h2>Perspektive, Interessen und Grenzen</h2><p>${esc(context)}</p></section></div><h2>Recherchezugänge und tatsächlicher Abrufstand</h2><p>Stand ${esc(formatDate(asOf))}. Ein technischer Abruf ist kein journalistisches Gütesiegel.</p>${feeds}<section class="term-section-card"><h2>Kosten- und Zugangsregel</h2><p>${esc(accessNote)}</p></section><p><a class="text-link" href="../">Alle Quellen und Auswahlkriterien</a> · <a class="text-link" href="../../">Zurück zum Wirkungsticker</a></p></article></main>`;
    write(`${root}/wirkungsticker/quellen/${id}/index.html`, pageShell({ title: `${source.name}: Quellenprofil`, description: why, canonical: profileLink(id), base: "../../../", body: profile, jsonLd: { "@context": "https://schema.org", "@type": "WebPage", name: `${source.name}: Quellenprofil`, url: profileLink(id), about: { "@type": "Organization", name: source.name, url: source.url } } }));
    routes.push(`wirkungsticker/quellen/${id}/`);
  }
  return routes;
}
