export const WirkungsradarSynonymMap = {
  "migration-kostet-nur": [
    "Migration kostet",
    "Auslaender kosten",
    "Sozialsysteme",
    "Sozialschmarotzer",
    "nie eingezahlt",
    "Fluechtlinge kosten",
    "Integration",
    "Zuwanderung",
    "Fachkraefte",
    "Kommunen ueberfordert",
  ],
  "deutschland-nur-zwei-prozent": [
    "2 Prozent",
    "zwei Prozent",
    "Deutschland kann nichts aendern",
    "China ist schuld",
    "wir sind zu klein",
    "CO2 Anteil Deutschland",
    "Territorialemissionen",
    "Territorialbilanz",
    "Konsumbilanz",
    "Scope 3",
    "Lieferkette",
  ],
  "windraeder-voegel-wald-beton-rueckbau": [
    "Windraeder toeten Voegel",
    "Fledermaeuse",
    "Wald",
    "Beton",
    "Rueckbau",
    "Sondermuell",
    "Rotorblaetter",
    "SF6",
    "Schwefelhexafluorid",
    "Recycling",
    "Windkraft Natur",
  ],
  "fusion-loest-das-energieproblem": [
    "Fusion",
    "Fusionskraftwerk",
    "ITER",
    "DEMO",
    "kleine Sonne",
    "unbegrenzte Energie",
    "Technikwunder",
    "thermisches Kraftwerk",
    "Turbine",
    "Tritium",
  ],
  "schulden-machen-oder-sparen": [
    "Schulden",
    "Schulden belasten unsere Kinder",
    "Staat pleite",
    "schwarze Null",
    "Refinanzierung",
    "Staatsanleihen",
    "Unterlassungsschuld",
    "Investitionen",
    "Zukunftsinvestitionen",
  ],
  "e-autos-schlimmer-als-verbrenner": [
    "E-Autos schlimmer",
    "Elektroauto",
    "Verbrenner",
    "Akku dreckig",
    "Batterie",
    "CO2 Rucksack",
    "Lebenszyklus",
    "Ladeinfrastruktur",
    "Oel",
  ],
  "e-fuels-retten-den-verbrenner": [
    "E-Fuels",
    "synthetische Kraftstoffe",
    "Verbrenner retten",
    "Technologieoffenheit",
    "weiter tanken",
    "Bestandsflotte",
    "Porsche Sprit",
    "Flugzeug",
    "Schiff",
    "E-Kerosin",
  ],
  "wasserstoff-fuer-alles": [
    "Wasserstoff",
    "H2",
    "Wasserstoffheizung",
    "Wasserstoffauto",
    "gruener Stahl",
    "Elektrolyse",
    "Rueckverstromung",
    "Dunkelflaute",
    "H2-ready",
  ],
  "arbeit-lohnt-sich-nicht-mehr": [
    "Buergergeld macht faul",
    "Arbeit lohnt sich nicht",
    "Totalverweigerer",
    "wer arbeitet ist der Dumme",
    "Lohnabstand",
    "Aufstocker",
    "Sozialneid",
    "Buergergeld",
  ],
  "co2-preis-oder-fossile-systemkosten": [
    "CO2 Preis",
    "CO2 Abzocke",
    "Klimageld",
    "Strafsteuer",
    "fossile Systemkosten",
    "Klimafolgekosten",
    "Benzin teurer",
    "Heizen teurer",
  ],
  "kernenergie-wieder-in-deutschland": [
    "Kernkraft zurueck",
    "Atomkraft",
    "AKW",
    "Grundlast",
    "Endlager",
    "SMR",
    "Versorgungssicherheit",
    "billiger Strom",
  ],
  "radwege-in-peru": [
    "Radwege Peru",
    "Steuergeld Ausland",
    "Entwicklungshilfe",
    "Entwicklungskredit",
    "KfW",
    "Lima",
    "Auslandsprojekte",
    "Wirkungspruefung",
  ],
  "ukraine-unterstuetzung-steuergeld": [
    "Ukraine Hilfe",
    "Steuergeld Ukraine",
    "Milliarden",
    "Korruption",
    "Krieg",
    "Wiederaufbau",
    "Sicherheit",
    "Kiel Tracker",
    "EU Ukraine Facility",
  ],
};
