import fs from 'node:fs';
import { escapeHtml as e, ImpactProcess, FeedbackLoop } from './explainer-components.mjs';
export const course = JSON.parse(fs.readFileSync(new URL('../../content/site/impact-controlling-course.json',import.meta.url),'utf8'));
const p = text => `<p>${e(text)}</p>`;
export function courseDiagram() {
  return `<figure class="course-comparison" aria-labelledby="course-comparison-title"><figcaption id="course-comparison-title">Vom sichtbaren Rückgang zum zusätzlich geschätzten Unterschied</figcaption><div class="course-bars">${[['Vorher',100,'before'],['Ohne Umstellung geschätzt',90,'comparison'],['Nachher beobachtet',60,'after']].map(([label,n,kind])=>`<div class="course-bar-row"><span>${label}</span><div class="course-bar-track"><div class="course-bar course-bar--${kind}" style="--bar:${n}%"><strong>${n} kg</strong></div></div></div>`).join('')}</div><p><strong>40 kg beobachteter Rückgang − 10 kg gemeinsame Entwicklung = 30 kg zusätzlicher Unterschied pro Tag.</strong> Schätzung unter den beschriebenen Vergleichsannahmen; keine reale Fallstudie.</p></figure>`;
}
export function indicatorCard(item, open=false) {
  return `<article class="card indicator-card" id="${e(item.id)}"><p class="card-kicker">${e(item.role)}</p><h3>${e(item.title)}</h3><p>${e(item.question)}</p><p class="indicator-result">${e(item.result)}</p><p>${e(item.meaning)}</p><details class="explanation-details"${open?' open':''}><summary>Formel, Rechnung und Anwendung</summary><div class="formula-block" aria-label="Formel">${e(item.formula)}</div><p><strong>Die Zeichen bedeuten:</strong> ${e(item.variables)}</p><p class="course-calculation"><strong>Eingesetzt:</strong> ${e(item.calculation)}</p><p><strong>Warum wichtig?</strong> ${e(item.importance)}</p><p><strong>So wird gemessen:</strong> ${e(item.measurement)}</p><p><strong>Grenzen:</strong> ${e(item.limit)}</p></details></article>`;
}
export function renderCourse() {
 const c=course, k=c.case;
 return `<nav class="course-toc" aria-label="Lernweg"><a href="#beispiel">1. Die Frage</a><a href="#vergleich">2. Der Vergleich</a><a href="#indikatoren">3. Die Kennzahlen</a><a href="#entscheidung">4. Die Entscheidung</a></nav>
<section class="section course-section" id="beispiel"><p class="hero-kicker">1 · Ein Fall, Schritt für Schritt</p><h2>${e(k.title)}</h2>${p(k.intro)}<p class="course-model-note">${e(k.status)}</p><div class="card-grid three">${[['Problem klären',k.problem],['Ziel prüfen',k.goal],['Alternativen vergleichen',k.options]].map(([title,text])=>`<article class="card"><h3>${e(title)}</h3>${p(text)}</article>`).join('')}</div>${ImpactProcess({label:'Der Wirkpfad der Schulküche',steps:k.mechanism,caption:'A = Auslöser/Handlung; M = Mechanismus; ΔZ = Zustandsveränderung; R = Referenz. Die Pfeile beschreiben eine zu prüfende Annahme.'})}</section>
<section class="section course-section section-soft" id="vergleich"><p class="hero-kicker">2 · Genau hinsehen</p><h2>40 Kilogramm weniger. Sind das schon 40 Kilogramm Wirkung?</h2>${courseDiagram()}${p(k.causality)}<details class="explanation-details"><summary>Welche Daten und Vergleichsgrenzen gelten?</summary>${p(k.boundary)}</details></section>
<section class="section course-section" id="begriffe"><h2>Die Begriffe in Alltagssprache</h2><p>Leistungszahlen und Wirkungskennzahlen ergänzen sich. Eine Liste von KII ist immer eine Auswahl für einen bestimmten Fall; es gibt keine universelle Pflichtliste für jede Organisation.</p><dl class="course-definitions">${c.terms.map(([term,text])=>`<div><dt>${e(term)}</dt><dd>${e(text)}</dd></div>`).join('')}</dl></section>
<section class="section course-section section-soft" id="indikatoren"><p class="hero-kicker">3 · Jede Kennzahl nachvollziehen</p><h2>Was messen wir, wie rechnen wir, was sagt es aus?</h2><p>Jede Karte zeigt Ergebnis und Bedeutung. Unter „Formel, Rechnung und Anwendung“ stehen die vollständige Berechnung, Messweise und Grenzen. Die ersten vier Karten erklären den Mengenvergleich; die weiteren prüfen Ziel, Nebenfolgen, Verteilung und Kosten.</p><div class="indicator-grid">${c.indicators.slice(0,9).map((x,i)=>indicatorCard(x,i===2)).join('')}</div></section>
<section class="section course-section" id="kennzahlen-vertiefung"><h2>Und wo bleiben IOI, T-SROI und WÖk-Netto-Wirkungsindex?</h2><p>Diese Größen verdichten bereits geprüfte Befunde. Sie sind keine zusätzlichen Messungen. Wer die Küche verstehen will, beginnt bei Abfall und Versorgung; eine Geldquote oder ein Gesamtprofil kommt bei Bedarf hinzu.</p><div class="indicator-grid">${c.indicators.slice(9).map(x=>indicatorCard(x)).join('')}</div><p><strong>Keine doppelte Bereinigung:</strong> In der Geldrechnung sind die 5.400 kg bereits um die Entwicklung der Vergleichsküche bereinigt. Der vorbereitete Fachrechner setzt deshalb Deadweight und Verdrängung auf 0 und Attribution auf 100 % des bereits bereinigten Stroms. Das sind ausdrücklich Modellannahmen, kein zusätzlicher Kausalnachweis.</p></section>
<section class="section course-section section-soft" id="entscheidung"><p class="hero-kicker">4 · Mit dem Ergebnis weiterarbeiten</p><h2>Eine Zahl ist erst hilfreich, wenn daraus eine bessere Entscheidung wird</h2><div class="card-grid three">${k.orders.map(([title,text])=>`<article class="card"><h3>${e(title)}</h3>${p(text)}</article>`).join('')}</div>${FeedbackLoop({title:'Prüfen → entscheiden → beobachten → nachsteuern',text:k.decision,action:'Reporting hält Befunde fest. Rückkopplung verändert auf dieser Grundlage die nächste Entscheidung.'})}<p><strong>Was noch offen bleibt:</strong> Vergleichbarkeit und Unsicherheit, Ernährung und Zugang, gruppenspezifische Folgen, veränderte Bestellungen sowie Umwelt- und Systemfolgen müssen in einem echten Pilotprojekt belegt werden. Die Lernzahlen ergeben keine Freigabe für eine reale Schule.</p></section>
<section class="section course-section" id="integration"><h2>Wie die WÖk vorhandene Ansätze zusammenführt</h2>${p(c.integration)}${p(c.publicContext)}<p><a href="/methodik/#staatliche-nachhaltigkeitsarchitektur">Bestehende staatliche Prüfarchitektur und objektspezifischer Zusatznutzen</a></p></section>
<section class="section course-section" id="quellen-beispiel"><h2>Quellen und fachlicher Stand</h2><p>Stand: 6. September 2026. Die Quellen begründen Methoden und Referenzrahmen; sie liefern keine Daten für die erfundene Schulküche.</p><ul>${c.sources.map(([title,url])=>`<li><a href="${e(url)}">${e(title)}</a></li>`).join('')}</ul></section>`;
}
export function renderSimpleCalculator() {
 const fields=(names)=>names.map(([name,label,val,help])=>`<label class="course-input" for="kitchen-${name}">${label}<input id="kitchen-${name}" name="${name}" type="number" min="0" max="1000000" step="any" value="${val}" required aria-describedby="kitchen-${name}-help"><small id="kitchen-${name}-help">${help}</small></label>`).join('');
 return `<section class="section course-section" id="einfacher-rechner"><div class="course-calculator" data-no-glossary data-kitchen-calculator><p class="hero-kicker">Erfundenes Lernbeispiel · drei kleine Schritte</p><h2>Was verändert die Schulküche?</h2><p>Die Beispielzahlen sind schon eingetragen. Du kannst sie unverändert durchgehen oder einzelne Werte ändern. Gerechnet wird für jeweils 1.000 Essen pro Tag; die gemeinsame Datenbasis bleibt sichtbar.</p><p data-course-progress class="course-progress">Schritt 1 von 3: Beobachtung</p><form class="course-form" novalidate>
<fieldset data-course-step="0"><legend>1. Was beobachten wir?</legend>${fields([['before','Essbarer Abfall vorher, in kg pro Tag',100,'Tagesmittel vor der Umstellung.'],['after','Essbarer Abfall nachher, in kg pro Tag',60,'Tagesmittel nach der Umstellung, bei gleicher Zahl Essen.']])}<p>Ein Rückgang zeigt eine Veränderung. Im nächsten Schritt prüfen wir, was auch ohne die Maßnahme passiert sein könnte.</p></fieldset>
<fieldset data-course-step="1"><legend>2. Was verändert sich in der Vergleichsküche?</legend>${fields([['comparisonBefore','Vergleichsküche vorher, in kg pro Tag',100,'Gleicher Zeitraum, gleiche Zahl Essen und gleiche Messmethode.'],['comparisonAfter','Vergleichsküche nachher, in kg pro Tag',90,'Die Vergleichsküche stellt zunächst nicht um.']])}<p>Der Vergleich hilft bei der Zurechnung. Ob er fachlich trägt, muss unabhängig von der Rechnung geprüft werden.</p></fieldset>
<fieldset data-course-step="2"><legend>3. Was bedeutet das für die weitere Planung?</legend>${fields([['days','Öffnungstage pro Jahr',180,'Die Hochrechnung nimmt einen stabilen Tageswert an.']])}<p>Nun betrachten wir die Jahresgröße. Versorgung, Zugang und Hygiene bleiben eigenständige Prüfaufgaben; sie lassen sich mit dieser Mengenrechnung nicht freigeben.</p></fieldset>
<p class="course-error" data-course-error role="alert"></p><div class="course-controls" hidden><button type="button" class="btn btn-secondary" data-course-back>Zurück</button><button type="button" class="btn btn-primary" data-course-next>Weiter zum Vergleich</button></div><button type="reset" class="text-link">Beispielwerte wiederherstellen</button></form>
<section class="course-live-result" aria-labelledby="kitchen-result-title"><h3 id="kitchen-result-title">Deine Rechnung</h3><div data-course-result role="status" aria-live="polite" aria-atomic="true"><p>Beispiel: (100 − 60) − (100 − 90) = <strong>30 kg zusätzlich vermiedener Abfall pro Tag</strong>. Bei 180 Tagen: <strong>5.400 kg als Jahreshochrechnung</strong>.</p></div></section><noscript><p>Die Beispielrechnung und alle Eingabeschritte bleiben lesbar. Für eigene interaktive Rechnungen wird JavaScript benötigt.</p></noscript><p><a href="/werkzeuge/impact-controlling/#zusaetzliche-veraenderung">Formel und Annahmen genau erklärt</a> · <a href="/werkzeuge/impact-controlling/#entscheidung">Wie daraus eine Entscheidung wird</a></p></div></section>`;
}
