import type { Metadata } from "next";
import { connection } from "next/server";
import Link from "next/link";
import { PortalNav } from "@/app/components/PortalNav";
import { SiteAnalyticsTracker } from "@/app/components/SiteAnalyticsTracker";
import { WirkungsradarQuickSignup } from "@/app/components/WirkungsradarQuickSignup";
import { AudienceModeSwitch } from "@/app/components/AudienceModeSwitch";
import { WirkungsraumLink } from "@/app/components/WirkungsraumLink";
import { subscriptionDeliveryReady } from "@/lib/wirkungsradar/subscriptions";
import "./globals.css";

export const metadata: Metadata = {
  title: { default: "Wirkungsportal Parlament", template: "%s · Wirkungsportal Parlament" },
  description: "Ein unabhängiges Portal des Instituts für Wirkungsökonomie zu Entscheidungen des Deutschen Bundestages.",
  metadataBase: new URL("https://parlament.wirkungsoekonomie.de"),
  applicationName: "Wirkungsportal Parlament",
  authors: [{ name: "Institut für Wirkungsökonomie", url: "https://wirkungsoekonomie.de" }],
  creator: "Institut für Wirkungsökonomie",
  publisher: "Institut für Wirkungsökonomie",
  icons: { icon: "/favicon.svg" }
};

export const dynamic = "force-dynamic";

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  // Every document needs the request-specific CSP nonce generated by
  // middleware. This intentionally disables static prerendering for the
  // public document shell; a cached page would carry somebody else's nonce.
  await connection();
  return (
    <html lang="de">
      <body>
        <a className="skip-link" href="#content">Zum Inhalt springen</a>
        <header>
          <div className="trust-band">
            <div className="shell trust-band-inner">
              <span>Unabhängiges Portal des Instituts für Wirkungsökonomie</span>
              <span aria-hidden="true">·</span>
              <Link href="/transparenz">Parteiunabhängig</Link>
              <span aria-hidden="true">·</span>
              <Link href="/methodik">Methodik offen</Link>
              <span aria-hidden="true">·</span>
              <Link href="/quellen">Quellen prüfbar</Link>
            </div>
          </div>
          <div className="site-header">
            <div className="shell header-inner">
              <Link href="/" className="brand" aria-label="Wirkungsportal Parlament, Startseite">
                <span className="brand-mark" aria-hidden="true">W</span>
                <span><strong>Wirkungsportal Parlament</strong><small>Parlamentarische Entscheidungen verstehen · Wirkungen prüfen · Entscheidungen rückkoppeln</small></span>
              </Link>
              <div className="header-navigation">
                <nav className="portal-utility-nav" aria-label="Schnellzugriffe">
                  <Link href="/suche">Suche</Link>
                  <WirkungsraumLink>Mein Wirkungsraum</WirkungsraumLink>
                  <AudienceModeSwitch />
                  <a className="ecosystem-link" href="https://wirkungsoekonomie.de">Wirkungsökonomie.de <span aria-hidden="true">↗</span></a>
                </nav>
                <PortalNav />
              </div>
            </div>
          </div>
        </header>
        <main id="content">{children}</main>
        <SiteAnalyticsTracker />
        <footer className="site-footer">
          <div className="shell">
            <section className="footer-signup" aria-labelledby="footer-signup-title">
              <div>
                <p className="eyebrow">Auf Wunsch informiert bleiben</p>
                <h2 id="footer-signup-title">Parlamentsradar-Updates per E-Mail</h2>
                <p>Kurze Hinweise zu anstehenden Entscheidungen und veröffentlichten Wirkungschecks. Sie entscheiden selbst, welche Themen Sie erhalten möchten.</p>
              </div>
              <WirkungsradarQuickSignup deliveryReady={subscriptionDeliveryReady()} />
            </section>
          </div>
          <div className="shell footer-grid">
            <div>
              <p className="eyebrow">Einordnung statt Parteibewertung</p>
              <h2>Vorher verstehen. Danach prüfen, was sich verändert.</h2>
              <p>Das Portal ist kein Angebot des Deutschen Bundestages. Es bewertet weder Menschen, Parteien noch Gesinnungen. Sein Maßstab, seine Quellen und seine Grenzen bleiben offen einsehbar; politische Entscheidungen trifft das Parlament.</p>
            </div>
            <div className="footer-links">
              <nav aria-label="Analyse" className="footer-nav">
                <h2>Analyse</h2>
                <Link href="/bevorstehend">Anstehende Entscheidungen</Link>
                <Link href="/entscheidungen">Entscheidungen</Link>
                <Link href="/historie">Historie</Link>
                <Link href="/fachanalysen">WÖk-Fachanalysen</Link>
                <Link href="/monitor">Wirkungsmonitor</Link>
              </nav>
              <nav aria-label="Transparenz" className="footer-nav">
                <h2>Transparenz</h2>
                <Link href="/methodik">Methodik</Link>
                <Link href="/transparenz">Über das Portal</Link>
                <Link href="/quellen">Quellenarchiv</Link>
                <Link href="/mandat-und-praxis">Mandat &amp; Praxis</Link>
                <Link href="/abgeordnete">Wirkungsprofile der Abgeordneten</Link>
                <Link href="/fraktionen">Wirkungsprofile der Fraktionen</Link>
              </nav>
              <nav aria-label="Kontakt" className="footer-nav">
                <h2>Kontakt</h2>
                <Link href="/wirkungsradar-updates">Parlamentsradar-Updates</Link>
                <Link href="/suche">Suche</Link>
                <WirkungsraumLink>Mein Wirkungsraum</WirkungsraumLink>
                <a href="mailto:wirkungscheck@wirkungsoekonomie.de?subject=Fehler%20oder%20Korrektur">Fehler oder Korrektur melden</a>
                <a href="mailto:wirkungscheck@wirkungsoekonomie.de?subject=Quelle%20oder%20Evidenz">Quelle oder Evidenz einreichen</a>
                <a href="mailto:wirkungscheck@wirkungsoekonomie.de?subject=Methodische%20Frage">Methodische Frage stellen</a>
                <a href="https://wirkungsoekonomie.de/impressum.html">Impressum</a>
                <a href="https://wirkungsoekonomie.de/datenschutz.html">Datenschutz</a>
                <a href="mailto:wirkungscheck@wirkungsoekonomie.de">wirkungscheck@wirkungsoekonomie.de</a>
              </nav>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
